### ISSUE TITLE
👥 UC004 - Creating new clients 

### ISSUE THREAD

**Issue by Odonata971** [SAE-S5-01-Developpement-avance/PathPilot-android-client#19]
### User Story

**As a** salesman connected on the app
**I want** to be able to create new clients, whether they are active clients or prospects.
**In order to** further grow the client base.

A client is defined by #20 

### Acceptation Test

**Given** a salesman that is connected to the client page
**When** he clicks on the button “Create client”
**Then** he gets redirected to the client creation page

**Given** a salesman that is connected and on the client creation page
**When** one or more of the fields is empty
**Then** a pop-up gets shown telling “Missing field : field(s) name(s)”

**Given** a salesman that is connected and on the client creation page and that has filled on fields
**When** he clicks on the “Save” button
**Then** he gets redirected to the client page with an indication saying “Client Created”

**Given** a salesman that is connected and on the client creation page and that has filled on fields
**When** the internet connection is done
**Then** he is notified of the problem
**And** he can't create the client but he can leave the interface
**And** the entered parameters are saved

**Comment by quentinformatique** [comment]
frontend done
