### ISSUE TITLE
Create login/sign-up pages mockup

### ISSUE THREAD

**Issue by quentinformatique** [SAE-S5-01-Developpement-avance/PathPilot-android-client#35]
# Description

This enabler is about creating the page's mockup for the login and sign-up pages

# Acceptance criterias
- [x] follow the application theme
- [x] User friendly UI 
- [x] responsive design

**Comment by quentinformatique** [comment]
@Francois389 ready to review

**Comment by Francois389** [comment]
Seems good to me
