### ISSUE TITLE
Rework file name in layout folder or drawable folder

### ISSUE THREAD

**Issue by quentinformatique** [SAE-S5-01-Developpement-avance/PathPilot-android-client#39]
### Summary

```markdown
Android doesn't allow you to make sub folders in either layout or drawable folder. But in order to keep a clean work environment, a good practice could be to use prefixes on every file in those folders.
```

### Background

Android doesn't allow you to make sub folders in either layout or drawable folders. But in order to keep a clean work environment, a good practice could be to use prefixes on every file in those folders.

### Describe the solution you'd like

 A good thing could be like:
- view_<ViewName>.xml
- component_<ComponentName>.xml
- icon_<IconName>.xml
- ...

### Describe alternatives you've considered

None

### Details

As of now, we only have a few files in those folders, so let's change their name in order to match the new prefixes

### Outcome

A clean work environment, an easy-to-use file structure, an easy to maintain app

**Comment by Mateofsr** [comment]
I refactor the files concerned.
And I'll be naming new files more regularly.
