### ISSUE TITLE
wrong component in a layout

### ISSUE THREAD

**Issue by quentinformatique** [SAE-S5-01-Developpement-avance/PathPilot-android-client#41]
### Summary

```markdown
For the sign-up page, an ImageView was used to display an icon used as a button.
```

### Background

For the sign-up page, an ImageView was used to display an icon used as button. 

### Describe the solution you'd like

use an ImageButton instead

### Describe alternatives you've considered

none

### Details

it has to be a button

### Outcome

have a button

**Comment by Mateofsr** [comment]
I fixed the view.
It's now a ImageButton.
